### ISSUE TITLE
Exception cause is hidden by AbstractLoadBalancerAwareClient.executeWithLoadBalancer

### ISSUE THREAD

**Issue by enisher** [Netflix/ribbon#258]
We got exception like this in production:
```
Caused by: com.netflix.client.ClientException: null
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:123) ~[ribbon-loadbalancer-2.0.0.jar!/:2.0.0]
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:81) ~[ribbon-loadbalancer-2.0.0.jar!/:2.0.0]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.forward(RibbonCommand.java:132) ~[spring-cloud-netflix-core-1.0.3.RELEASE.jar!/:1.0.3.RELEASE]
```

Client exception doesn't have a cause. That makes the reason of that exception totally unclear. 
Original exception erased by this code:
```
        } catch (Exception e) {
            Throwable t = e.getCause();
            if (t instanceof ClientException) {
                throw (ClientException) t;
            } else {
                throw new ClientException(t);
            }
        }
```
In case when `e` doesn't have any cause it is caught and replaced with `ClientException`.

Unfortunately I don't know how to reproduce the issue.

**Comment by enisher** [comment]
Sorry. That has been fixed by @mattnelson in d98065c.
