### ISSUE TITLE
com.netflix.client.http.HttpRequest doesn't support PATCH.

### ISSUE THREAD

**Issue by 6sco** [Netflix/ribbon#285]
Any reason why com.netflix.client.http.HttpRequest doesn't support PATCH method ?

Caused by: java.lang.IllegalArgumentException: No enum constant com.netflix.client.http.HttpRequest.Verb.PATCH
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_65]
	at com.netflix.client.http.HttpRequest$Verb.valueOf(HttpRequest.java:39) ~[ribbon-httpclient-2.0.0.jar!/:2.0.0]
	at org.springframework.cloud.netflix.ribbon.RibbonClientHttpRequestFactory.createRequest(RibbonClientHttpRequestFactory.java:70) ~[spring-cloud-netflix-core-1.0.7.RELEASE.jar!/:1.0.7.RELEASE]
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:77) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:565) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:484) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

**Comment by spencergibb** [comment]
IIRC, it's the version of the actual http client that doesn't support it. Newer versions of spring cloud don't use `RibbonClientHttpRequestFactory`, they use the default `RestTemplate` http client, so patch isn't an issue.

**Comment by mhauzer** [comment]
Hello, it's year 2019 here! ;) I am using Spring Cloud Greenwich.RELEASE and it is still a problem. When a client service is trying to call PATCH method of a microservice registered in Eureka then it is served with "Invalid HTTP method: PATCH" message. 

Calling the endpoint manually with Postman results with a proper behaviour so the server implementation seems OK.
