### ISSUE TITLE
SocketTimeoutException(connect time out) is not judged as a ConnectionException 

### ISSUE THREAD

**Issue by HashZhang** [Netflix/ribbon#359]
while retry request, there are many preconditions should be matched. 

But for SocketTimeoutException(connect time out) , it is not  judged as a ConnectionException  so that it will not be retried

here is the related source code RequestSpecificRetryHandler.java:
```
protected List<Class<? extends Throwable>> connectionRelated = Lists
			.<Class<? extends Throwable>> newArrayList(SocketException.class);
public boolean isConnectionException(Throwable e) {
        return Utils.isPresentAsCause(e, connectionRelated);
    }
```

**Comment by HashZhang** [comment]
Not all SocketTimeoutException should be retried, but for that exception with msg "connect time out", it should be retried

**Comment by HashZhang** [comment]
While the timeout is set less than 1000, "java.net.SocketTimeoutException: connect timed out" will be thrown.  while it is large than 1000, "java.net.ConnectException: Connection refused: connect" will be thrown

```
public static void main(String[] args) throws IOException {
        Socket socket = new Socket();
        try {
            socket.connect(new InetSocketAddress("127.0.0.1", 8080), 500);
        } catch (Exception e) {
            e.printStackTrace();
        }
        socket = new Socket();
        socket.connect(new InetSocketAddress("127.0.0.1", 8080), 1100);

    }
```

the output is:
```
java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.hash.test.TestRxJava.main(TestRxJava.java:14)
Exception in thread "main" java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.hash.test.TestRxJava.main(TestRxJava.java:19)
```

**Comment by HashZhang** [comment]
for both of the exceptions, they should be retried.

**Comment by penghbgit** [comment]
Have these two exception retryes been fixed? In which version?

**Comment by yhmingyue** [comment]
到现在还是没有处理这个问题吗？

**Comment by yhmingyue** [comment]
SocketTimeoutException still cannot be retried, 
Is this problem not going to be dealt with?

**Comment by yhmingyue** [comment]
SocketTimeoutException 还是不能重试，
这个问题不处理了吗？
